name: CI Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        wget https://github.com/jgm/pandoc/releases/download/2.9/pandoc-2.9-1-amd64.deb
        sudo dpkg -i pandoc-2.9-1-amd64.deb
        python -m pip install --upgrade pip
        pip install pandoc
    - name: Generate document
      run: |
        chmod +x generate-document.sh
        ./generate-document.sh
    - name: Archive document
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_CycloneDX-SBOM-Guide-SNAPSHOT-en.docx
        path: OWASP_CycloneDX-SBOM-Guide-SNAPSHOT-en.docx
